Add Breaking Changes
starkinfra/sdk-python pull request #43
Opened 2022-08-03 14:05 UTC by xavier-stark

2022-08-04 14:08 UTC, joaogpw-stark requested changes

2022-08-04 18:55 UTC, xavier-stark commented on starkinfra/event/__event.py
> +    - subscription [string]: service that triggered this Event. ex: "pix-request.in", "pix-request.out", "pix-reversal.in", "pix-reversal.out", "issuing-card", "issuing-invoice", "issuing-purchase",
Na doc em Webhook subscriptions
https://starkinfra.com/docs/api#webhook

2022-08-04 19:32 UTC, xavier-stark commented on tests/sdk/testDynamicBrcode.py
> +            description="teste Python",
Lembrei

2022-08-04 19:32 UTC, xavier-stark commented on starkinfra/__init__.py
> +from .creditpreview.__creditpreview import CreditPreview
Nao entendi

2022-08-04 19:33 UTC, xavier-stark commented on starkinfra/creditpreview/__creditpreview.py
> +def _parse_credit(credit, type):
Foi definido que é melhor o jeito que está implementado

2022-08-05 16:54 UTC, joaogpw-stark requested changes

2022-08-05 16:54 UTC, joaogpw-stark commented on starkinfra/__init__.py
> +from .creditpreview.__creditpreview import CreditPreview
Opa, o CreditNotePreview

2022-08-05 16:54 UTC, joaogpw-stark commented on starkinfra/creditpreview/__creditpreview.py
> +
Voce não corrigiu isso e marcou como resolvido?

2022-08-09 21:20 UTC, joaogpw-stark requested changes

2022-08-09 21:20 UTC, joaogpw-stark commented on CHANGELOG.md
> +- amount to nominal_amount fine_amount to fine, interest_amount to interest and discount_amount to discounts on response_due method of DynamicBrcode resource
amount to nominal_amount, fine_amount to fine, interest_amount to interest, and discount_amount to discounts on response_due method of DynamicBrcode resource

2022-08-10 14:54 UTC, joaogpw-stark approved these changes

2022-08-10 17:20 UTC, merged