Add a python-core new version
starkinfra/sdk-python pull request #65
Opened 2023-05-19 21:03 UTC by luistarkbank

2023-05-22 14:23 UTC, xavier-stark requested changes

2023-05-22 14:23 UTC, xavier-stark commented on requirements.txt
> +starkcore==0.1.1
faltou o changelog

2023-05-22 14:23 UTC, xavier-stark commented on requirements.txt
> +starkcore==0.1.1
rodou todos os testes?

2023-06-20 20:47 UTC, xavier-stark requested changes

2023-06-20 20:47 UTC, xavier-stark commented on CHANGELOG.md
> +- update core version
Changed update core version fica estranho

A ideia é levar o Changed em consideração que nem em cima:
Added metadata parameter to IssuingPurchase resource

2026-07-15 02:38 UTC, edu-stark commented
Closing this PR automatically due to more than 6 months of inactivity (no activity since before 2026-01-01). Please reopen if this work is still relevant.

2026-07-15 02:38 UTC, closed without merging