Fix request prefix
starkinfra/sdk-python pull request #80
Opened 2024-06-10 22:16 UTC by leoKagohara-Stark

2024-06-10 23:24 UTC, luistarkbank approved these changes

2024-06-18 14:33 UTC, luistarkbank approved these changes

2024-06-18 14:34 UTC, luistarkbank approved these changes

2024-06-25 00:53 UTC, luistarkbank commented on starkinfra/request/__request.py
> +    - body [dict]: request parameters. ex: {"pix-request": [{"amount": 100, "name": "Iron Bank S.A.", "taxId": "20.018.183/0001-80"}]}
só "request" só

2024-06-25 00:53 UTC, luistarkbank commented on starkinfra/request/__request.py
> +        prefix=request_methods_prefix
raiseException

2024-06-25 22:21 UTC, luistarkbank requested changes

2024-06-25 22:21 UTC, luistarkbank commented on starkinfra/request/__request.py
> +    - body [dict]: request parameters. ex: {"pix-request": [{"amount": 100, "name": "Iron Bank S.A.", "taxId": "20.018.183/0001-80"}]}
"request" leo, {"request": [{"amount": 100, "name": "Iron Bank S.A.", "taxId": "20.018.183/0001-80"}]}

2024-06-25 22:21 UTC, luistarkbank commented on starkinfra/request/__request.py
> +        prefix=request_methods_prefix
?? raiseException

2024-06-25 22:21 UTC, luistarkbank commented on starkinfra/request/__request.py
> +        prefix=request_methods_prefix
raiseException

2024-06-28 01:30 UTC, luistarkbank requested changes

2024-06-28 01:30 UTC, luistarkbank commented on starkinfra/request/__request.py
> +    - body [dict]: request parameters. ex: {"pix-request": [{"amount": 100, "name": "Iron Bank S.A.", "taxId": "20.018.183/0001-80"}]}
o nome do elemento do json que recebe a lista de elementos do recurso é sempre o ultimo nome do recurso no plural, nesse caso de "pix-request" ficaria "requests", desculpa por não ser claro no meu comentario anterior

2024-06-28 21:48 UTC, leoKagohara-Stark commented on starkinfra/request/__request.py
> +    - body [dict]: request parameters. ex: {"pix-request": [{"amount": 100, "name": "Iron Bank S.A.", "taxId": "20.018.183/0001-80"}]}
boa!
Alterei aqui, valeu!

2024-07-01 14:29 UTC, luistarkbank requested changes

2024-07-01 14:29 UTC, luistarkbank commented on starkinfra/request/__request.py
> +    - body [dict]: request parameters. ex: {"request": [{"amount": 100, "name": "Iron Bank S.A.", "taxId": "20.018.183/0001-80"}]}
plural kj "requests"

2024-07-01 19:04 UTC, luistarkbank approved these changes

2024-07-01 19:11 UTC, merged